/**
 * Type declaration for the compiled OvraBid contract module served from
 * /contract/ovraBid/contract/index.js (generated by the Compact compiler,
 * synced by scripts/sync-web-assets.mjs).
 */
declare module '/contract/ovraBid/contract/index.js' {
  export const Contract: unknown;
  export const ledger: (state: unknown) => Record<string, unknown>;
  export const witnesses: Record<string, never>;
  export type Ledger = unknown;
}
