/**
 * Loads the compiled OvraBid contract in the browser and joins the deployed
 * preprod instance with the user's private state.
 *
 * The compiled contract module is served from
 * web/public/contract/ovraBid/contract/index.js (synced by
 * scripts/sync-web-assets.mjs after `npm run compile`).
 */
import { CompiledContract, type Contract } from '@midnight-ntwrk/midnight-js-protocol/compact-js';
import { findDeployedContract } from '@midnight-ntwrk/midnight-js-contracts';
import type { FoundContract } from '@midnight-ntwrk/midnight-js-contracts';
import type { OvraBidProviders } from './providers';
import { PREPROD_CONTRACT_ADDRESS } from './types';
import type { OvraBidPrivateState } from './private-state-types';
import { witnesses } from './witnesses';

export const CONTRACT_NAME = 'ovraBid';
export const PRIVATE_STATE_ID = 'ovraBidPrivateState';

export const CONTRACT_MODULE_URL = '/contract/ovraBid/contract/index.js';

let cachedArtifacts: { Contract: unknown } | null = null;

export async function loadContractArtifacts(): Promise<{ Contract: unknown }> {
  if (cachedArtifacts) return cachedArtifacts;
  // The compiled module is a bundled ESM file generated by the Compact
  // compiler — imported at runtime from the site's static assets. The
  // specifier is a variable so neither tsc nor Vite tries to resolve it at
  // build time (plus @vite-ignore for the dev server).
  const mod = (await import(/* @vite-ignore */ CONTRACT_MODULE_URL)) as {
    Contract: unknown;
  };
  cachedArtifacts = mod;
  return mod;
}

/**
 * Builds the CompiledContract with the localSecretKey witness wired in. The
 * witness reads the user's secret key from their private state at proving
 * time — it is never a UI input. zkConfig file assets (prover/verifier keys,
 * ZKIR) are served from the same static tree.
 */
export async function buildCompiledContract(): Promise<unknown> {
  const artifacts = await loadContractArtifacts();
  const make = CompiledContract.make as unknown as (
    name: string,
    ctor: unknown,
  ) => unknown;
  const base = make(CONTRACT_NAME, artifacts.Contract);
  const withWitnesses = (
    CompiledContract.withWitnesses as unknown as (c: unknown, w: unknown) => unknown
  )(base, witnesses);
  return (CompiledContract.withCompiledFileAssets as unknown as (
    c: unknown,
    p: string,
  ) => unknown)(withWitnesses, '/contract/ovraBid');
}

export type OvraBidFoundContract = FoundContract<Contract.Any>;

export async function joinContract(
  providers: OvraBidProviders,
  initialPrivateState: OvraBidPrivateState,
): Promise<OvraBidFoundContract> {
  const compiledContract = await buildCompiledContract();
  // Type boundary: the compiled artifact's circuit-id union is structurally
  // compatible with the providers'; midnight-js's conditional generics cannot
  // verify it across the runtime import, so the join is one cast — the same
  // boundary the Node-side deploy script has.
  return findDeployedContract(providers as never, {
    compiledContract,
    contractAddress: PREPROD_CONTRACT_ADDRESS,
    privateStateId: PRIVATE_STATE_ID,
    initialPrivateState,
  } as never) as Promise<OvraBidFoundContract>;
}
