/**
 * Generates a buffer containing a series of randomly generated bytes.
 * (Same helper as the Midnight example contracts' test utils.)
 */
export const randomBytes = (length: number): Uint8Array => {
  const bytes = new Uint8Array(length);
  crypto.getRandomValues(bytes);
  return bytes;
};
